### Root

GET http://localhost:8000


### Cocktail API

GET http://localhost:8000/api/cocktail

###

GET http://localhost:8000/api/cocktail?name=none

###

GET http://localhost:8000/api/cocktail?name=アイリッシュコーヒー

###

GET http://localhost:8000/api/cocktail/all
